import {
  Heading1, Type, MousePointerClick, Image as ImageIcon, Minus, Square,
  Layout, List, Link2, Code2, Columns3, Rows3, BadgeCheck, Star, Quote,
  Mail, Video, MapPin, Share2, Table, Menu, MessageCircle, Clock, GalleryHorizontalEnd,
  MousePointerSquareDashed
} from 'lucide-react'

const W = {
  heading: '<h2 style="font-size:40px;line-height:1.08;font-weight:800;letter-spacing:-0.03em;margin:0 0 16px;color:#0f172a;">Título avançado</h2>',
  richText: '<div style="font-size:17px;line-height:1.75;color:#475569;"><p style="margin:0 0 12px;">Texto rico com <strong>negrito</strong>, <em>ênfase</em> e <a href="#" style="color:#6d71f0;">link</a>.</p><ul style="margin:0;padding-left:20px;"><li>Primeiro ponto</li><li>Segundo ponto</li></ul></div>',
  buttonDual: '<div style="display:flex;gap:12px;flex-wrap:wrap;align-items:center;"><a href="#" style="display:inline-flex;padding:13px 22px;border-radius:999px;background:#6d71f0;color:#fff;text-decoration:none;font-weight:700;">Principal</a><a href="#" style="display:inline-flex;padding:13px 22px;border-radius:999px;background:#fff;color:#0f172a;text-decoration:none;font-weight:700;border:1px solid #dbe3ef;">Secundário</a></div>',
  icon: '<div style="width:48px;height:48px;border-radius:14px;background:#eef2ff;color:#6d71f0;display:flex;align-items:center;justify-content:center;font-size:26px;font-weight:800;">★</div>',
  iconBox: '<div style="display:flex;gap:14px;align-items:flex-start;padding:20px;border:1px solid #e5e7eb;border-radius:12px;background:#fff;"><div style="width:42px;height:42px;border-radius:12px;background:#eef2ff;color:#6d71f0;display:flex;align-items:center;justify-content:center;font-weight:800;">★</div><div><h3 style="font-size:18px;margin:0 0 6px;color:#0f172a;">Recurso</h3><p style="margin:0;color:#64748b;line-height:1.5;">Descrição curta do recurso.</p></div></div>',
  image: '<img src="https://placehold.co/900x520/e5e7eb/64748b?text=Imagem" alt="Imagem" style="width:100%;max-width:760px;height:auto;border-radius:14px;display:block;">',
  gallery: '<div style="display:grid;grid-template-columns:repeat(3,1fr);gap:12px;"><img src="https://placehold.co/400x300/e5e7eb/64748b?text=1" alt="" style="width:100%;border-radius:12px;"><img src="https://placehold.co/400x300/dbeafe/1d4ed8?text=2" alt="" style="width:100%;border-radius:12px;"><img src="https://placehold.co/400x300/dcfce7/15803d?text=3" alt="" style="width:100%;border-radius:12px;"></div>',
  carousel: '<div style="display:flex;gap:14px;overflow-x:auto;scroll-snap-type:x mandatory;padding:8px 0;"><div style="min-width:280px;scroll-snap-align:start;border-radius:16px;background:#f8fafc;padding:28px;border:1px solid #e5e7eb;">Slide 1</div><div style="min-width:280px;scroll-snap-align:start;border-radius:16px;background:#eef2ff;padding:28px;border:1px solid #c7d2fe;">Slide 2</div><div style="min-width:280px;scroll-snap-align:start;border-radius:16px;background:#ecfdf5;padding:28px;border:1px solid #bbf7d0;">Slide 3</div></div>',
  video: '<video controls style="width:100%;max-width:720px;border-radius:14px;display:block;background:#111827;"><source src="" type="video/mp4"></video>',
  embed: '<div style="position:relative;width:100%;max-width:760px;aspect-ratio:16/9;border-radius:14px;overflow:hidden;background:#111827;color:#fff;display:flex;align-items:center;justify-content:center;">Embed / iframe</div>',
  map: '<div style="height:320px;border-radius:16px;background:linear-gradient(135deg,#e5e7eb,#f8fafc);border:1px solid #d1d5db;display:flex;align-items:center;justify-content:center;color:#64748b;font-weight:700;">Mapa / localização</div>',
  form: '<form style="display:grid;gap:12px;max-width:520px;padding:24px;border:1px solid #e5e7eb;border-radius:14px;background:#fff;"><input placeholder="Nome" style="padding:12px;border:1px solid #d1d5db;border-radius:8px;"><input placeholder="E-mail" type="email" style="padding:12px;border:1px solid #d1d5db;border-radius:8px;"><textarea placeholder="Mensagem" style="padding:12px;border:1px solid #d1d5db;border-radius:8px;min-height:120px;"></textarea><button style="padding:12px 18px;border:none;border-radius:8px;background:#6d71f0;color:#fff;font-weight:700;">Enviar</button></form>',
  input: '<input placeholder="Digite aqui" style="width:100%;max-width:420px;padding:13px 14px;border:1px solid #d1d5db;border-radius:10px;font-size:15px;">',
  accordion: '<div style="border:1px solid #e5e7eb;border-radius:14px;overflow:hidden;background:#fff;"><details open style="padding:16px;border-bottom:1px solid #e5e7eb;"><summary style="font-weight:700;cursor:pointer;">Pergunta 1</summary><p style="margin:10px 0 0;color:#64748b;">Resposta do item.</p></details><details style="padding:16px;"><summary style="font-weight:700;cursor:pointer;">Pergunta 2</summary><p style="margin:10px 0 0;color:#64748b;">Resposta do item.</p></details></div>',
  tabs: '<div><div style="display:flex;gap:8px;margin-bottom:12px;"><button style="padding:10px 14px;border-radius:999px;border:0;background:#6d71f0;color:#fff;font-weight:700;">Tab 1</button><button style="padding:10px 14px;border-radius:999px;border:1px solid #e5e7eb;background:#fff;">Tab 2</button></div><div style="padding:20px;border:1px solid #e5e7eb;border-radius:14px;background:#fff;">Conteúdo da aba.</div></div>',
  toggle: '<details style="padding:16px;border:1px solid #e5e7eb;border-radius:14px;background:#fff;"><summary style="font-weight:700;cursor:pointer;">Abrir conteúdo</summary><p style="margin:10px 0 0;color:#64748b;">Texto oculto.</p></details>',
  modal: '<div style="padding:24px;border:1px solid #e5e7eb;border-radius:16px;background:#fff;box-shadow:0 18px 50px rgba(15,23,42,.14);max-width:420px;"><h3 style="margin:0 0 8px;">Popup</h3><p style="margin:0 0 16px;color:#64748b;">Conteúdo do modal.</p><a href="#" style="display:inline-flex;padding:11px 18px;border-radius:999px;background:#6d71f0;color:#fff;text-decoration:none;font-weight:700;">Ação</a></div>',
  alert: '<div style="padding:14px 16px;border-radius:12px;background:#fff7ed;border:1px solid #fed7aa;color:#9a3412;font-weight:700;">Mensagem de alerta</div>',
  counter: '<div style="font-size:48px;line-height:1;font-weight:900;color:#6d71f0;">1.250</div>',
  progress: '<div style="max-width:520px;"><div style="display:flex;justify-content:space-between;margin-bottom:8px;font-weight:700;"><span>Progresso</span><span>72%</span></div><div style="height:12px;border-radius:999px;background:#e5e7eb;overflow:hidden;"><div style="width:72%;height:100%;background:#6d71f0;border-radius:999px;"></div></div></div>',
  testimonial: '<blockquote style="padding:24px;border:1px solid #e5e7eb;border-radius:16px;background:#fff;max-width:560px;"><p style="font-size:18px;line-height:1.55;margin:0 0 16px;color:#334155;">“Depoimento do cliente sobre o resultado.”</p><footer style="font-weight:800;color:#0f172a;">Nome do cliente</footer></blockquote>',
  card: '<div style="padding:28px;background:#fff;border-radius:16px;border:1px solid #e5e7eb;box-shadow:0 4px 12px rgba(0,0,0,.04);max-width:400px;"><h3 style="font-size:20px;margin:0 0 8px;color:#0f172a;">Título do card</h3><p style="color:#6b7280;line-height:1.5;margin:0 0 16px;">Texto descritivo do card.</p><a href="#" style="color:#6d71f0;font-weight:700;text-decoration:none;">Saiba mais</a></div>',
  pricing: '<div style="padding:30px;border:1px solid #e5e7eb;border-radius:18px;background:#fff;max-width:360px;"><h3 style="margin:0 0 8px;">Plano Pro</h3><div style="font-size:42px;font-weight:900;margin-bottom:14px;">R$99</div><ul style="line-height:2;padding-left:20px;color:#475569;"><li>Recurso 1</li><li>Recurso 2</li><li>Recurso 3</li></ul><a href="#" style="display:flex;justify-content:center;margin-top:18px;padding:13px;border-radius:999px;background:#6d71f0;color:#fff;text-decoration:none;font-weight:800;">Comprar</a></div>',
  iconList: '<ul style="list-style:none;padding:0;margin:0;display:grid;gap:10px;"><li>✓ Primeiro benefício</li><li>✓ Segundo benefício</li><li>✓ Terceiro benefício</li></ul>',
  breadcrumb: '<nav style="font-size:14px;color:#64748b;"><a href="#" style="color:#6d71f0;text-decoration:none;">Início</a> / <a href="#" style="color:#6d71f0;text-decoration:none;">Categoria</a> / Página</nav>',
  nav: '<nav style="display:flex;gap:20px;align-items:center;flex-wrap:wrap;"><a href="#" style="text-decoration:none;color:#0f172a;font-weight:700;">Início</a><a href="#" style="text-decoration:none;color:#0f172a;font-weight:700;">Sobre</a><a href="#" style="text-decoration:none;color:#0f172a;font-weight:700;">Contato</a></nav>',
  header: '<header style="padding:20px 24px;border-bottom:1px solid #e5e7eb;background:#fff;"><div style="max-width:1120px;margin:0 auto;display:flex;justify-content:space-between;align-items:center;gap:20px;"><strong style="font-size:22px;">Marca</strong><nav style="display:flex;gap:18px;"><a href="#" style="color:#0f172a;text-decoration:none;">Home</a><a href="#" style="color:#0f172a;text-decoration:none;">Sobre</a></nav></div></header>',
  footer: '<footer style="padding:48px 24px;background:#0f172a;color:#fff;"><div style="max-width:1120px;margin:0 auto;display:flex;justify-content:space-between;gap:24px;flex-wrap:wrap;"><strong>Marca</strong><p style="margin:0;color:#cbd5e1;">© 2026 Todos os direitos reservados.</p></div></footer>',
  hero: '<section style="padding:80px 24px;background:#f8fafc;"><div style="max-width:1100px;margin:0 auto;text-align:center;"><h1 style="font-size:52px;line-height:1.05;margin:0 0 18px;color:#0f172a;">Título principal</h1><p style="font-size:20px;line-height:1.6;color:#475569;margin:0 auto 28px;max-width:720px;">Descrição curta do produto ou oferta.</p><a href="#" style="display:inline-flex;padding:14px 24px;border-radius:999px;background:#6d71f0;color:#fff;text-decoration:none;font-weight:700;">Chamada principal</a></div></section>',
  cta: '<section style="padding:54px 24px;background:#6d71f0;color:#fff;border-radius:18px;text-align:center;"><h2 style="font-size:36px;margin:0 0 12px;">Chamada para ação</h2><p style="margin:0 0 22px;color:#e0e7ff;">Texto curto de apoio.</p><a href="#" style="display:inline-flex;padding:13px 22px;border-radius:999px;background:#fff;color:#4338ca;text-decoration:none;font-weight:800;">Começar</a></section>',
  faq: '<section style="padding:40px 0;"><h2 style="font-size:32px;margin:0 0 18px;">Perguntas frequentes</h2><div style="display:grid;gap:10px;"><details style="padding:16px;border:1px solid #e5e7eb;border-radius:12px;"><summary style="font-weight:700;">Pergunta</summary><p style="color:#64748b;">Resposta.</p></details></div></section>',
  flex: '<div style="display:flex;gap:16px;align-items:center;flex-wrap:wrap;padding:16px;border:1px dashed #cbd5e1;border-radius:14px;"><div style="padding:18px;background:#f8fafc;border-radius:10px;">Item</div><div style="padding:18px;background:#eef2ff;border-radius:10px;">Item</div></div>',
  grid: '<div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:18px;padding:24px 0;"><div style="padding:22px;border:1px solid #e5e7eb;border-radius:14px;background:#fff;">Card 1</div><div style="padding:22px;border:1px solid #e5e7eb;border-radius:14px;background:#fff;">Card 2</div><div style="padding:22px;border:1px solid #e5e7eb;border-radius:14px;background:#fff;">Card 3</div></div>',
  spacer: '<div style="height:48px;"></div>',
  shape: '<div style="height:80px;background:linear-gradient(135deg,#6d71f0,#2bbf88);clip-path:polygon(0 0,100% 0,100% 55%,0 100%);"></div>',
  html: '<div><!-- HTML personalizado --></div>',
  css: '<style>/* CSS personalizado */</style>',
  shortcode: '<div data-shortcode="[shortcode]" style="padding:16px;border:1px dashed #94a3b8;border-radius:12px;color:#64748b;">[shortcode]</div>',
  whatsapp: '<a href="https://wa.me/5500000000000" style="display:inline-flex;align-items:center;gap:8px;padding:13px 20px;border-radius:999px;background:#25d366;color:#fff;text-decoration:none;font-weight:800;">WhatsApp</a>',
  social: '<div style="display:flex;gap:10px;"><a href="#" style="width:38px;height:38px;border-radius:999px;background:#0f172a;color:#fff;display:flex;align-items:center;justify-content:center;text-decoration:none;">f</a><a href="#" style="width:38px;height:38px;border-radius:999px;background:#0f172a;color:#fff;display:flex;align-items:center;justify-content:center;text-decoration:none;">in</a><a href="#" style="width:38px;height:38px;border-radius:999px;background:#0f172a;color:#fff;display:flex;align-items:center;justify-content:center;text-decoration:none;">x</a></div>',
  lottie: '<div style="height:220px;border-radius:16px;background:#f8fafc;border:1px dashed #cbd5e1;display:flex;align-items:center;justify-content:center;color:#64748b;font-weight:700;">Lottie / JSON</div>',
  beforeAfter: '<div style="display:grid;grid-template-columns:1fr 1fr;gap:8px;max-width:760px;"><img src="https://placehold.co/420x300/e5e7eb/64748b?text=Antes" alt="Antes" style="width:100%;border-radius:12px;"><img src="https://placehold.co/420x300/dcfce7/15803d?text=Depois" alt="Depois" style="width:100%;border-radius:12px;"></div>',
  timeline: '<ol style="list-style:none;margin:0;padding:0;display:grid;gap:14px;"><li style="padding-left:24px;border-left:3px solid #6d71f0;"><strong>Etapa 1</strong><p style="margin:4px 0 0;color:#64748b;">Descrição.</p></li><li style="padding-left:24px;border-left:3px solid #6d71f0;"><strong>Etapa 2</strong><p style="margin:4px 0 0;color:#64748b;">Descrição.</p></li></ol>',
  steps: '<div style="display:grid;grid-template-columns:repeat(3,1fr);gap:16px;"><div><strong>01</strong><h3>Planejar</h3></div><div><strong>02</strong><h3>Executar</h3></div><div><strong>03</strong><h3>Medir</h3></div></div>',
  table: '<table style="width:100%;border-collapse:collapse;"><thead><tr><th style="padding:12px;border:1px solid #e5e7eb;text-align:left;">Item</th><th style="padding:12px;border:1px solid #e5e7eb;text-align:left;">Valor</th></tr></thead><tbody><tr><td style="padding:12px;border:1px solid #e5e7eb;">Linha 1</td><td style="padding:12px;border:1px solid #e5e7eb;">100</td></tr></tbody></table>',
  badge: '<span style="display:inline-flex;align-items:center;gap:6px;padding:7px 12px;background:#ecfdf5;color:#047857;border:1px solid #a7f3d0;border-radius:999px;font-size:13px;font-weight:700;">Badge</span>',
  marquee: '<marquee style="padding:12px;background:#0f172a;color:#fff;border-radius:12px;font-weight:700;">Texto em movimento</marquee>',
  anchor: '<a id="secao" href="#secao" style="color:#6d71f0;text-decoration:underline;">Âncora interna</a>',
}

export const ELEMENT_TEMPLATES = [
  { category: 'Texto', items: [
    { id: 'heading', label: 'Heading', icon: Heading1, html: W.heading },
    { id: 'richtext', label: 'Texto rico', icon: Type, html: W.richText },
    { id: 'quote', label: 'Citação', icon: Quote, html: '<blockquote style="padding:20px 24px;border-left:4px solid #6d71f0;background:#f8fafc;color:#334155;font-size:18px;line-height:1.55;margin:20px 0;">Texto da citação.</blockquote>' },
    { id: 'list', label: 'Lista ícones', icon: List, html: W.iconList },
    { id: 'badge', label: 'Badge/Pill', icon: BadgeCheck, html: W.badge },
    { id: 'counter', label: 'Contador', icon: Star, html: W.counter },
  ]},
  { category: 'Ações', items: [
    { id: 'button', label: 'Botão', icon: MousePointerClick, html: '<a href="#" style="display:inline-block;padding:12px 24px;background:#6d71f0;color:#fff;border-radius:8px;text-decoration:none;font-weight:600;">Clique aqui</a>' },
    { id: 'buttondual', label: 'Botão duplo', icon: MousePointerClick, html: W.buttonDual },
    { id: 'whatsapp', label: 'WhatsApp', icon: MessageCircle, html: W.whatsapp },
    { id: 'social', label: 'Social Icons', icon: Share2, html: W.social },
    { id: 'anchor', label: 'Âncora', icon: Link2, html: W.anchor },
    { id: 'breadcrumb', label: 'Breadcrumb', icon: Link2, html: W.breadcrumb },
  ]},
  { category: 'Mídia', items: [
    { id: 'image', label: 'Imagem', icon: ImageIcon, html: W.image },
    { id: 'gallery', label: 'Galeria', icon: GalleryHorizontalEnd, html: W.gallery },
    { id: 'carousel', label: 'Carrossel', icon: GalleryHorizontalEnd, html: W.carousel },
    { id: 'video', label: 'Vídeo', icon: Video, html: W.video },
    { id: 'embed', label: 'Embed', icon: Code2, html: W.embed },
    { id: 'map', label: 'Mapa', icon: MapPin, html: W.map },
    { id: 'lottie', label: 'Lottie/JSON', icon: Star, html: W.lottie },
    { id: 'beforeafter', label: 'Antes/Depois', icon: ImageIcon, html: W.beforeAfter },
  ]},
  { category: 'Layout', items: [
    { id: 'section', label: 'Seção', icon: Layout, html: '<section style="padding:60px 20px;background:#f9fafb;"><div style="max-width:1200px;margin:0 auto;"><h2 style="font-size:32px;margin-bottom:16px;">Nova seção</h2><p style="color:#6b7280;line-height:1.6;">Descrição da seção.</p></div></section>' },
    { id: 'container', label: 'Container', icon: Square, html: '<div style="padding:24px;background:#fff;border-radius:12px;border:1px solid #e5e7eb;"><p style="margin:0;">Conteúdo do container.</p></div>' },
    { id: 'flex', label: 'Flex Container', icon: Layout, html: W.flex },
    { id: 'grid', label: 'Grid', icon: Rows3, html: W.grid },
    { id: 'columns2', label: '2 Colunas', icon: Columns3, html: '<div style="display:grid;grid-template-columns:1fr 1fr;gap:24px;padding:24px 0;"><div><h3>Coluna 1</h3><p>Conteúdo.</p></div><div><h3>Coluna 2</h3><p>Conteúdo.</p></div></div>' },
    { id: 'columns3', label: '3 Colunas', icon: Columns3, html: '<div style="display:grid;grid-template-columns:repeat(3,1fr);gap:24px;padding:24px 0;"><div>Item 1</div><div>Item 2</div><div>Item 3</div></div>' },
    { id: 'columns4', label: '4 Colunas', icon: Columns3, html: '<div style="display:grid;grid-template-columns:repeat(4,1fr);gap:20px;padding:24px 0;"><div>Item 1</div><div>Item 2</div><div>Item 3</div><div>Item 4</div></div>' },
    { id: 'spacer', label: 'Espaço', icon: Square, html: W.spacer },
    { id: 'divider', label: 'Divisor', icon: Minus, html: '<hr style="border:none;border-top:1px solid #e5e7eb;margin:24px 0;">' },
    { id: 'shape', label: 'Shape divider', icon: Minus, html: W.shape },
  ]},
  { category: 'Seções', items: [
    { id: 'header', label: 'Header', icon: Menu, html: W.header },
    { id: 'hero', label: 'Hero', icon: Layout, html: W.hero },
    { id: 'cta', label: 'CTA', icon: MousePointerClick, html: W.cta },
    { id: 'faq', label: 'FAQ', icon: List, html: W.faq },
    { id: 'footer', label: 'Footer', icon: Layout, html: W.footer },
    { id: 'timeline', label: 'Timeline', icon: Clock, html: W.timeline },
    { id: 'steps', label: 'Steps', icon: Columns3, html: W.steps },
  ]},
  { category: 'Interação', items: [
    { id: 'form', label: 'Formulário', icon: Mail, html: W.form },
    { id: 'input', label: 'Input', icon: Type, html: W.input },
    { id: 'accordion', label: 'Accordion', icon: List, html: W.accordion },
    { id: 'tabs', label: 'Tabs', icon: Rows3, html: W.tabs },
    { id: 'toggle', label: 'Toggle', icon: MousePointerSquareDashed, html: W.toggle },
    { id: 'modal', label: 'Modal/Popup', icon: Square, html: W.modal },
    { id: 'alert', label: 'Alert', icon: BadgeCheck, html: W.alert },
  ]},
  { category: 'Cards e Dados', items: [
    { id: 'icon', label: 'Ícone', icon: Star, html: W.icon },
    { id: 'iconbox', label: 'Icon Box', icon: Star, html: W.iconBox },
    { id: 'card', label: 'Card', icon: Square, html: W.card },
    { id: 'pricing', label: 'Pricing', icon: Square, html: W.pricing },
    { id: 'testimonial', label: 'Depoimento', icon: Quote, html: W.testimonial },
    { id: 'progress', label: 'Progresso', icon: Minus, html: W.progress },
    { id: 'table', label: 'Tabela', icon: Table, html: W.table },
  ]},
  { category: 'Avançado', items: [
    { id: 'html', label: 'HTML', icon: Code2, html: W.html },
    { id: 'css', label: 'CSS', icon: Code2, html: W.css },
    { id: 'shortcode', label: 'Shortcode', icon: Code2, html: W.shortcode },
    { id: 'marquee', label: 'Marquee', icon: Type, html: W.marquee },
  ]},
]
